apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    ad-app: mysql
spec:
  type: NodePort
  selector:
    ad-app: mysql
  ports:
    - name: mysql
      port: 3306
      nodePort: 30306

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    ad-app: mysql
spec:
  replicas: 1
  selector:
    ad-app: mysql
  template:
    metadata:
      labels:
        ad-app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
        - containerPort: 3306
          name: mysql
